### ISSUE TITLE
update to autotrace 0.40.0

### ISSUE THREAD

**Issue by jnweiger** [scottvr/autotrace-win64-binaries#1]
Hey Scott, if you want to refresh your windows binary here, please check out the latest version of the source at https://github.com/jnweiger/autotrace , thanks!

**Comment by scottvr** [comment]
Thanks for the notice! It seems with the latest versions, there is no need for me to maintain binary releases anymore. Good work!

**Comment by jnweiger** [comment]
Yes, you can simply refer to the windows release of 0.40 at  https://github.com/autotrace/autotrace/releases -- it has a crude nsis installer thing for windows. You could do me a favour and test it. I rarely use windows...

**Comment by scottvr** [comment]
I tested the packages and the installer. The resultant executables do work on my 64-bit Windows 7 machine. A few comments: Maybe change the default install location to not use the "Program Files (x86)" directory as it does now. Since your binaries are 64-bit, "\\Program Files\\" is where they go.  Since you include libs in the install path too- another (32-bit) application looking for the DLL for libiconv, for example, will choke when it finds your x86-64 DLL in its "SYSWOW64" executable path. In other words, autotrace.exe will work from this directory, but you run a risk of breaking some other app by putting 64-bit shared libs in the 32-bit Program Files path, which is probably not-desired. 

I am going to go ahead and build your 0.40 since my target was statically linked (and with libpng, which I notice you didn't build support for) and replace what's in my repo with new binaries. Presumably a fair number of people have used/are using this repo due to its mention in a few different docs/threads, so I don't want to render the legacy docs out there non-working.

**Comment by jnweiger** [comment]
If I did it right, the two issues should be fixed. There are new builds at https://github.com/autotrace/autotrace/releases/tag/travis-20190108.39

**Comment by scottvr** [comment]
Hey cool! Thanks.  I have updated the README here to point to your repo.
